version: "3.8"

services:
  ui:
    build:
      context: ..
      dockerfile: mental-arithmetic-ui-test/Dockerfile
    image: myorg/ui:latest
    container_name: ui
    ports:
      - "7070:80"
    networks:
      - web


networks:
  web:
    external: false
